CREATE TABLE GENERO (
  GENID NUMBER NOT NULL, 
  GENNOMBRE VARCHAR2(40) NOT NULL, 
   CONSTRAINT "GENERO_PK" PRIMARY KEY ("GENID")
   );
Insert into GENERO (GENID,GENNOMBRE) values (10,'ACCION');
Insert into GENERO (GENID,GENNOMBRE) values (20,'COMEDIA');
Insert into GENERO (GENID,GENNOMBRE) values (30,'DRAMA');
Insert into GENERO (GENID,GENNOMBRE) values (40,'AVENTURAS');
Insert into GENERO (GENID,GENNOMBRE) values (50,'TERROR');
Insert into GENERO (GENID,GENNOMBRE) values (60,'CIENCIA_FICCION');
  CREATE TABLE PELICULA 
   (  PELID NUMBER, 
  TITULO VARCHAR2(50), 
  DIRECTOR VARCHAR2(20), 
  GENERO NUMBER, 
  DURACION NUMBER, 
  PRECIO NUMBER, 
  FECHA DATE,
CONSTRAINT "PELICULA_PK" PRIMARY KEY ("PELID"),
CONSTRAINT "GENERO_FK" FOREIGN KEY ("GENERO")
    REFERENCES GENERO ("GENID")
   );  
Insert into PELICULA 
(PELID,TITULO,DIRECTOR,GENERO,DURACION,PRECIO,FECHA) values (1,'El señor de los anillos','Peter Jackson',60,'178','12000',to_date('25/12/01','DD/MM/RR'));
Insert into PELICULA 
(PELID,TITULO,DIRECTOR,GENERO,DURACION,PRECIO,FECHA) values 
(2,'starwars','George Lucas',60,'121','15000',to_date('07/11/77','DD/MM/RR'));
Insert into PELICULA 
(PELID,TITULO,DIRECTOR,GENERO,DURACION,PRECIO,FECHA) values 
(3,'Jumanji','Joe Johnston',40,'104','10000',to_date('15/12/95','DD/MM/RR'));
Insert into PELICULA 
(PELID,TITULO,DIRECTOR,GENERO,DURACION,PRECIO,FECHA) values (4,'El aro','Gore Verbinski',50,'116','13000',to_date('18/10/02','DD/MM/RR'));
Insert into PELICULA 
(PELID,TITULO,DIRECTOR,GENERO,DURACION,PRECIO,FECHA) values 
(5,'Matrix','Lana Wachowski',60,'150','13000',to_date('21/05/99','DD/MM/RR'));
Insert into PELICULA 
(PELID,TITULO,DIRECTOR,GENERO,DURACION,PRECIO,FECHA) values 
(6,'Terminator','James Cameron',60,'108','10000',to_date('26/10/84','DD/MM/RR'));
